/**
 * src/components/StormFX.tsx
 * Lightning bolt overlay — gated to Thor mode only.
 * In Gear 5 mode renders null.
 *
 * Triggers:
 *  1. Window event 'thor:strike' (existing P0 behaviour)
 *  2. ScrollTrigger onEnter for each [data-section] element
 *     (added in P1 — inside withMotion so motion-off disables it)
 *
 * SVG bolt paths are now generated by generateLightningPath() from
 * src/lib/lightning.ts for a cleaner midpoint-displacement look while
 * retaining the existing branching logic for secondary paths.
 */
import { useEffect, useRef, useState } from 'react';
import { useMode, useEffectsActive } from '../stores/mode';
import { ScrollTrigger, withMotion } from '../lib/gsap';
import { generateLightningPath } from '../lib/lightning';

type Point = { x: number; y: number };

type Bolt = {
  id: number;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  born: number;
  thickness: number;
  paths: string[]; // SVG "d" strings from generateLightningPath
};

const LIFETIME = 900;

function createBolt(id: number): Bolt {
  const width = 160 + Math.random() * 120;
  const height = 260 + Math.random() * 180;
  const thickness = 1.6 + Math.random() * 0.9;

  // Main bolt: top-center → bottom-center with horizontal wander
  const startX = width / 2 + (Math.random() - 0.5) * width * 0.3;
  const endX   = width / 2 + (Math.random() - 0.5) * width * 0.3;
  const mainPath = generateLightningPath(
    { x: startX, y: 0 },
    { x: endX, y: height },
    /* displacement */ width * 0.28,
    /* detail */ 5,
  );

  // Branch paths
  const branchCount = Math.random() > 0.6 ? 2 : 1;
  const branches: string[] = [];
  for (let b = 0; b < branchCount; b++) {
    // Branch from somewhere in the middle of the bolt
    const t = 0.3 + Math.random() * 0.4;
    const branchStart: Point = {
      x: startX + (endX - startX) * t + (Math.random() - 0.5) * 30,
      y: height * t,
    };
    const direction = Math.random() > 0.5 ? 1 : -1;
    const branchLen = height * (0.25 + Math.random() * 0.25);
    const branchEnd: Point = {
      x: branchStart.x + direction * branchLen * 0.35,
      y: branchStart.y + branchLen,
    };
    branches.push(
      generateLightningPath(branchStart, branchEnd, width * 0.14, 3),
    );
  }

  return {
    id,
    x: Math.random() * 100,
    y: 10 + Math.random() * 60,
    width,
    height,
    rotation: (Math.random() - 0.5) * 18,
    born: performance.now(),
    thickness,
    paths: [mainPath, ...branches],
  };
}

export default function StormFX() {
  const mode  = useMode();
  const isThor = mode === 'thor';
  const effectsActive = useEffectsActive();
  // Storm effects only render when Thor mode is engaged AND the user has
  // explicitly opted in via the Hero stat-tile. Mode-only rendering would
  // ignore the user's opt-in toggle.
  const stormOn = isThor && effectsActive;
  const [bolts, setBolts] = useState<Bolt[]>([]);
  const idRef = useRef(0);

  // Always clear bolts whenever the storm is turned off so the user sees an
  // immediate response when they tap the tile to "rest".
  useEffect(() => {
    if (!stormOn) setBolts([]);
  }, [stormOn]);

  // ---- Existing event-driven trigger ----
  useEffect(() => {
    if (!stormOn) {
      setBolts([]);
      return;
    }

    // Track every live cleanup timer so rapid strikes don't leak handles.
    const cleanupTimers = new Set<number>();

    function spawn() {
      const count = 2 + Math.floor(Math.random() * 3);
      // Cap at 8 existing + new bolts so even if cleanup misfires we stay bounded.
      setBolts((prev) => [
        ...prev.slice(-8),
        ...Array.from({ length: count }, () => createBolt(++idRef.current)),
      ]);

      const handle = window.setTimeout(() => {
        cleanupTimers.delete(handle);
        const cutoff = performance.now() - LIFETIME;
        setBolts((prev) => prev.filter((bolt) => bolt.born > cutoff));
      }, LIFETIME + 40) as unknown as number;
      cleanupTimers.add(handle);
    }

    const onStrike = () => spawn();
    spawn(); // initial burst on mount
    window.addEventListener('thor:strike', onStrike);
    return () => {
      window.removeEventListener('thor:strike', onStrike);
      // Clear every outstanding handle — not just the last one.
      cleanupTimers.forEach((h) => window.clearTimeout(h));
      cleanupTimers.clear();
    };
  }, [stormOn]);

  // ---- ScrollTrigger-driven trigger (P1 addition) ----
  // Only attaches scroll triggers when storm is opted-in. Detaches on rest.
  useEffect(() => {
    if (!stormOn) return;

    let triggers: ReturnType<typeof ScrollTrigger.create>[] = [];
    // 1.5 s cooldown flag to avoid strobing consecutive sections
    let cooldownUntil = 0;

    withMotion(() => {
      const sections = document.querySelectorAll<HTMLElement>('[data-section]');
      sections.forEach((el) => {
        const t = ScrollTrigger.create({
          trigger: el,
          start: 'top 80%',
          onEnter: () => {
            const now = performance.now();
            if (now < cooldownUntil) return;
            cooldownUntil = now + 1500;
            window.dispatchEvent(new Event('thor:strike'));
          },
        });
        triggers.push(t);
      });
    });

    return () => {
      triggers.forEach((t) => t.kill());
      triggers = [];
    };
  }, [stormOn]);

  if (!isThor) return null;

  return (
    <div
      aria-hidden
      className="pointer-events-none fixed inset-0 z-[35] mix-blend-screen"
      style={{ contain: 'layout paint size' }}
    >
      <div key={bolts[bolts.length - 1]?.id ?? 0} className="absolute inset-0 animate-[stormFlash_720ms_ease-out]" />
      {bolts.map((bolt) => {
        const gradientId = `bolt-gradient-${bolt.id}`;
        return (
          <svg
            key={bolt.id}
            viewBox={`0 0 ${bolt.width} ${bolt.height}`}
            className="absolute animate-[bolt_620ms_cubic-bezier(.18,.88,.32,1)]"
            style={{
              left: `${bolt.x}vw`,
              top: `${bolt.y}vh`,
              width: `${bolt.width}px`,
              height: `${bolt.height}px`,
              transform: `translate(-50%, -18%) rotate(${bolt.rotation}deg)`,
              filter:
                'drop-shadow(0 0 18px rgba(170,220,255,0.65)) drop-shadow(0 0 42px rgba(110,190,255,0.3))',
            }}
          >
            <defs>
              <linearGradient id={gradientId} x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%"   stopColor="rgba(255,255,255,0)" />
                <stop offset="15%"  stopColor="rgba(195,235,255,0.8)" />
                <stop offset="55%"  stopColor="rgba(255,255,255,1)" />
                <stop offset="85%"  stopColor="rgba(150,215,255,0.85)" />
                <stop offset="100%" stopColor="rgba(255,255,255,0)" />
              </linearGradient>
            </defs>
            {bolt.paths.map((d, index) => (
              <path
                key={index}
                d={d}
                fill="none"
                stroke={`url(#${gradientId})`}
                strokeWidth={(index === 0 ? bolt.thickness : bolt.thickness * 0.65) * 1.6}
                strokeLinecap="round"
                strokeLinejoin="round"
                opacity={index === 0 ? 1 : 0.8}
              />
            ))}
          </svg>
        );
      })}

      <style>{`
        @keyframes stormFlash {
          0% { background: rgba(255,255,255,0); }
          12% { background: rgba(180,220,255,0.18); }
          28% { background: rgba(110,160,255,0.12); }
          100% { background: rgba(255,255,255,0); }
        }
        @keyframes bolt {
          0%   { opacity: 0; filter: blur(1.5px); }
          16%  { opacity: 1; filter: blur(0.4px); }
          32%  { opacity: 0.65; filter: blur(0.8px); }
          48%  { opacity: 0.95; filter: blur(0.2px); }
          100% { opacity: 0; filter: blur(2px); }
        }
      `}</style>
    </div>
  );
}
