-- =============================================================================
-- 0012_pgvector_embeddings_translations.sql
-- =============================================================================
-- Purpose:
--   M4 — data layer for RAG (embeddings) + i18n (translations_cache) + adds
--   the `problem` column on projects so the M3 detail page can round-trip
--   the problem / role / writeup tuple cleanly.

-- 1) pgvector — RAG retrieval (M5). Initially installed in `public`; moved to
--    `extensions` schema in 0015_security_hardening per Supabase best practice.
create extension if not exists vector;

-- 2) `problem` column on projects. Existing `subtitle` -> tagline and
--    `description` -> writeup are reused; only `problem` was genuinely missing.
alter table public.projects
  add column if not exists problem text not null default '';

comment on column public.projects.problem is
  'Short blurb describing the problem the project solves. Rendered on the project detail page above "My role" and "What it does".';

-- 3) Embeddings table — chunks of project + section copy, embedded for RAG.
create table if not exists public.embeddings (
  id           uuid primary key default gen_random_uuid(),
  source_table text not null,
  source_id    uuid,
  source_key   text,
  chunk        text not null,
  embedding    vector(1536) not null,
  updated_at   timestamptz not null default now(),
  check (source_id is not null or source_key is not null)
);

comment on table public.embeddings is
  'RAG corpus: 1536-d text-embedding-3-small chunks of projects + site_content. Refreshed nightly by Vercel cron.';

create index if not exists embeddings_embedding_cosine_idx
  on public.embeddings
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create index if not exists embeddings_source_idx
  on public.embeddings (source_table, source_id, source_key);

-- 4) Translations cache — EN canonical, HE generated by AI Gateway, cached
--    forever (key = sha256 of source + content_type).
create table if not exists public.translations_cache (
  key          text primary key,
  source_table text not null,
  source_id    uuid,
  content_type text not null default 'text',
  en           text not null,
  he           text not null,
  created_at   timestamptz not null default now()
);

comment on table public.translations_cache is
  'Cached AI-generated EN<->HE translations for page content. Key = sha256(en + content_type). M6 populates via ai/translate Server Action.';

create index if not exists translations_cache_source_idx
  on public.translations_cache (source_table, source_id);

-- 5) RLS — both tables public-read (SSR + RAG retrieval), admin-only writes.
alter table public.embeddings enable row level security;
alter table public.translations_cache enable row level security;

create policy "embeddings_public_read"
  on public.embeddings for select
  to anon, authenticated
  using (true);

create policy "embeddings_admin_write"
  on public.embeddings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "translations_public_read"
  on public.translations_cache for select
  to anon, authenticated
  using (true);

create policy "translations_admin_write"
  on public.translations_cache for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
